### ISSUE TITLE
Conditional_VAE.py does not work

### ISSUE THREAD

**Issue by hellojinwoo** [graviraja/pytorch-sample-codes#1]
The 225th line `train_loss = train()` makes the following error : 
> RuntimeError: Expected object of backend CPU but got backend CUDA for argument #4 'mat1'

Can you fix the code please?

**Comment by graviraja** [comment]
@hellojinwoo Can you let me know where are you running the code. It should be run completely in a cpu or a gpu. `device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')` this part is essential. Make sure you are initializing the device properly.

**Comment by gulvarol** [comment]
Adding the line `model = model.to(device)` fixes this for me.
