### ISSUE TITLE
sampling from uniform distribution instead of normal

### ISSUE THREAD

**Issue by sdv4** [graviraja/pytorch-sample-codes#3]
In the forward function of your VAE, you compute the epsilons by using torch.rand_like, which samples from a uniform distribution. Shouldn't we be sampling from a gaussian?

**Comment by graviraja** [comment]
@sdv4  torch.randn_like returns a tensor from a normal distribution with mean 0 and variance 1. It does not sample from uniform distribution. Please refer to the documentation of torch.randn_like [here](https://pytorch.org/docs/stable/torch.html?highlight=randn_like#torch.randn_like).
